server:
  port: 7003
eureka:
  instance:
    hostname: eureka7003.com
  #需要在本地C盘中的hosts配置eureka7002.com的路径 127.0.0.1，不然使用localhost靠谱，默认127.0.0.1
  client:
    fetch-registry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    register-with-eureka: false #false表示不向注册中心注册自己。

    #设置与eureka Server交互的地址查询服务和注册中心服务都需要依赖这个地址
    service-url:
      defaultZone: http://eureka7001.com/7001/eureka/,http://eureka7002.com/7002/eureka/