redis:
  host: 192.168.132.201
  port: 6379
server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
    username: root
    password: 123456

mybatis:
  mapperLocations: classpath:com.tedu.mapper/*.xml

logging:
  path: ./logs
  level:
    com.tedu.mapper: debug