server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
    username: root
    password: cjx990725

mybatis:
  mapperLocations: classpath:com.tedu.mall.mapper/*.xml

logging:
  path: ./logs
  level:
    com.tedu.mall.mapper: debug
